version: '3.6'
services:
  ingest:
    image: docker.pkg.github.com/nerdcubed/ftl/ftl-server
    restart: unless-stopped
    ports:
      - 8084:8084/tcp
      - 8088:8088/tcp
      - 9000-9100:9000-9100/udp
      - 20000-20100:20000-20100/udp
    environment:
      - DOCKER_IP=<host ip>
  web:
    image: docker.pkg.github.com/nerdcubed/ftl/ftl-web
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    environment:
      - FTL_CLIENT_INGEST_SERVER=<ingest url>
